name: Generate Data

on:
  schedule:
    - cron: '0 */3 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  senado:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Refresh Cuatrenio 2022-2026
        run: |
          npm run refresh -- --tipo senado --cuatrenio "2022-2026" --report

      - name: Check if there's changes
        id: check-changes-first
        run: |
          if [[ -z $(git diff --exit-code -- output) ]]; then
            echo "No changes to commit"
            echo "CHANGES=false" >> $GITHUB_OUTPUT
          else
            echo "There are changes"
            echo "CHANGES=true" >> $GITHUB_OUTPUT
          fi

      - name: Refresh Cuatrenio 2018-2022
        if: steps.check-changes-first.outputs.CHANGES == 'true'
        run: |
          npm run refresh -- --tipo senado --cuatrenio "2018-2022" --report

      - name: Check if there's changes again
        id: check-changes-second
        run: |
          if [[ -z $(git diff --exit-code -- output) ]]; then
            echo "No changes to commit"
            echo "CHANGES=false" >> $GITHUB_OUTPUT
          else
            echo "There are changes"
            echo "CHANGES=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit data
        if: steps.check-changes-second.outputs.CHANGES == 'true'
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add output
          git add db/database.db
          git commit -m "Update data [Senado]"
          git push

  camara:
    if: ${{ always() }}
    needs: senado
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Refresh Cuatrenio 2022-2026
        run: |
          npm run refresh -- --tipo camara --cuatrenio "2022-2026" --report

      - name: Check if there's changes
        id: check-changes-first
        run: |
          if [[ -z $(git diff --exit-code -- output) ]]; then
            echo "No changes to commit"
            echo "CHANGES=false" >> $GITHUB_OUTPUT
          else
            echo "There are changes"
            echo "CHANGES=true" >> $GITHUB_OUTPUT
          fi

      - name: Refresh Cuatrenio 2018-2022
        if: steps.check-changes-first.outputs.CHANGES == 'true'
        run: |
          npm run refresh -- --tipo camara --cuatrenio "2018-2022" --report

      - name: Check if there's changes again
        id: check-changes-second
        run: |
          if [[ -z $(git diff --exit-code -- output) ]]; then
            echo "No changes to commit"
            echo "CHANGES=false" >> $GITHUB_OUTPUT
          else
            echo "There are changes"
            echo "CHANGES=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit data
        if: steps.check-changes-second.outputs.CHANGES == 'true'
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add output
          git add db/database.db
          git commit -m "Update data [Camara]"
          git push

  pal:
    if: ${{ always() }}
    needs: camara
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Refresh Cuatrenio 2022-2026
        run: |
          npm run refresh -- --tipo PAL --cuatrenio "2022-2026" --report

      - name: Check if there's changes
        id: check-changes-first
        run: |
          if [[ -z $(git diff --exit-code -- output) ]]; then
            echo "No changes to commit"
            echo "CHANGES=false" >> $GITHUB_OUTPUT
          else
            echo "There are changes"
            echo "CHANGES=true" >> $GITHUB_OUTPUT
          fi

      - name: Refresh Cuatrenio 2018-2022
        if: steps.check-changes-first.outputs.CHANGES == 'true'
        run: |
          npm run refresh -- --tipo PAL --cuatrenio "2018-2022" --report

      - name: Check if there's changes again
        id: check-changes-second
        run: |
          if [[ -z $(git diff --exit-code -- output) ]]; then
            echo "No changes to commit"
            echo "CHANGES=false" >> $GITHUB_OUTPUT
          else
            echo "There are changes"
            echo "CHANGES=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit data
        if: steps.check-changes-second.outputs.CHANGES == 'true'
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add output
          git add db/database.db
          git commit -m "Update data [PAL]"
          git push
